import type { Achievement, AchievementCategory, AchievementMetric } from '@/domain/gamification'

type Def = Omit<Achievement, 'unlockedAt'>

function def(
  id: string,
  title: string,
  description: string,
  category: AchievementCategory,
  metric: AchievementMetric,
  threshold: number,
  icon: string,
  xpReward: number,
  coinReward: number,
): Def {
  return {
    id,
    key: id.replace(/-/g, '_'),
    category,
    metric,
    threshold,
    title,
    description,
    icon,
    xpReward,
    coinReward,
  }
}

/** Canonical catalog — single source of truth for seed/upsert (~100 achievements) */
export const ACHIEVEMENT_DEFINITIONS: Def[] = [
  // ── Tasks: created ──────────────────────────────────────────
  def('first-task', 'First Step', 'Create your first task', 'tasks', 'tasks_created', 1, 'sparkles', 10, 5),
  def('tasks-created-3', 'Getting Organized', 'Create 5 tasks', 'tasks', 'tasks_created', 5, 'list', 15, 8),
  def('tasks-created-5', 'List Maker', 'Create 10 tasks', 'tasks', 'tasks_created', 10, 'list', 20, 10),
  def('tasks-created-10', 'Planner', 'Create 25 tasks', 'tasks', 'tasks_created', 25, 'clipboard', 35, 15),
  def('tasks-created-15', 'Roadmapper', 'Create 40 tasks', 'tasks', 'tasks_created', 40, 'map', 45, 20),
  def('tasks-created-25', 'Backlog Builder', 'Create 60 tasks', 'tasks', 'tasks_created', 60, 'layers', 60, 30),
  def('tasks-created-40', 'Queue Commander', 'Create 100 tasks', 'tasks', 'tasks_created', 100, 'clipboard', 80, 40),
  def('tasks-created-50', 'Idea Factory', 'Create 125 tasks', 'tasks', 'tasks_created', 125, 'lightbulb', 100, 50),
  def('tasks-created-75', 'Architect of Work', 'Create 200 tasks', 'tasks', 'tasks_created', 200, 'building', 140, 65),
  def('tasks-created-100', 'Infinite Inbox', 'Create 250 tasks', 'tasks', 'tasks_created', 250, 'inbox', 175, 80),
  def('tasks-created-150', 'Catalog Keeper', 'Create 400 tasks', 'tasks', 'tasks_created', 400, 'layers', 225, 110),
  def('tasks-created-250', 'Visionary', 'Create 650 tasks', 'tasks', 'tasks_created', 650, 'eye', 300, 150),
  def('tasks-created-500', 'Oracle', 'Create 1250 tasks', 'tasks', 'tasks_created', 1250, 'orbit', 500, 250),

  // ── Tasks: completed ────────────────────────────────────────
  def('tasks-done-1', 'First Win', 'Complete your first task', 'tasks', 'tasks_completed', 1, 'check', 15, 8),
  def('tasks-done-3', 'Triple Check', 'Complete 5 tasks', 'tasks', 'tasks_completed', 5, 'check-circle', 20, 10),
  def('tasks-done-5', 'Warm-up', 'Complete 10 tasks', 'tasks', 'tasks_completed', 10, 'thumbs-up', 25, 12),
  def('ten-tasks', 'Getting Momentum', 'Complete 25 tasks', 'tasks', 'tasks_completed', 25, 'zap', 50, 25),
  def('tasks-done-15', 'Finisher', 'Complete 40 tasks', 'tasks', 'tasks_completed', 40, 'flag', 65, 30),
  def('tasks-done-20', 'Closer', 'Complete 50 tasks', 'tasks', 'tasks_completed', 50, 'flag', 70, 35),
  def('tasks-done-25', 'Quarter Century', 'Complete 60 tasks', 'tasks', 'tasks_completed', 60, 'medal', 80, 40),
  def('tasks-done-35', 'Resolve', 'Complete 85 tasks', 'tasks', 'tasks_completed', 85, 'bolt', 90, 45),
  def('fifty-tasks', 'Task Machine', 'Complete 125 tasks', 'tasks', 'tasks_completed', 125, 'rocket', 100, 50),
  def('tasks-done-75', 'Unstoppable', 'Complete 200 tasks', 'tasks', 'tasks_completed', 200, 'bolt', 150, 70),
  def('century-club', 'Century Club', 'Complete 250 tasks', 'tasks', 'tasks_completed', 250, 'trophy', 200, 100),
  def('tasks-done-125', 'Relentless', 'Complete 350 tasks', 'tasks', 'tasks_completed', 350, 'flame', 225, 110),
  def('tasks-done-150', 'Grinder', 'Complete 450 tasks', 'tasks', 'tasks_completed', 450, 'hammer', 250, 120),
  def('tasks-done-200', 'Powerhouse', 'Complete 500 tasks', 'tasks', 'tasks_completed', 500, 'dumbbell', 300, 150),
  def('tasks-done-250', 'Titan', 'Complete 650 tasks', 'tasks', 'tasks_completed', 650, 'shield', 350, 175),
  def('tasks-done-300', 'Legend', 'Complete 750 tasks', 'tasks', 'tasks_completed', 750, 'crown', 400, 200),
  def('tasks-done-400', 'Apex', 'Complete 1000 tasks', 'tasks', 'tasks_completed', 1000, 'mountain', 500, 250),
  def('tasks-done-500', 'Immortal', 'Complete 1500 tasks', 'tasks', 'tasks_completed', 1500, 'gem', 600, 300),
  def('tasks-done-750', 'Mythmaker', 'Complete 2000 tasks', 'tasks', 'tasks_completed', 2000, 'diamond', 800, 400),
  def('tasks-done-1000', 'Thousand Cuts', 'Complete 2500 tasks', 'tasks', 'tasks_completed', 2500, 'swords', 1200, 600),

  // ── Focus / Pomodoro ────────────────────────────────────────
  def('focus-first', 'Focus Starter', 'Finish your first pomodoro session', 'focus', 'pomodoro_sessions', 1, 'timer', 25, 10),
  def('focus-2', 'Second Wind', 'Finish 5 pomodoro sessions', 'focus', 'pomodoro_sessions', 5, 'timer', 30, 12),
  def('focus-3', 'Getting Warm', 'Finish 8 pomodoro sessions', 'focus', 'pomodoro_sessions', 8, 'coffee', 40, 15),
  def('focus-5', 'Hour of Power', 'Finish 12 pomodoro sessions', 'focus', 'pomodoro_sessions', 12, 'hourglass', 55, 25),
  def('focus-7', 'Session Stack', 'Finish 18 pomodoro sessions', 'focus', 'pomodoro_sessions', 18, 'layers', 65, 30),
  def('deep-work', 'Deep Work', 'Finish 25 pomodoro sessions', 'focus', 'pomodoro_sessions', 25, 'brain', 75, 40),
  def('focus-15', 'Concentration', 'Finish 40 pomodoro sessions', 'focus', 'pomodoro_sessions', 40, 'focus', 100, 50),
  def('focus-20', 'Immersion', 'Finish 50 pomodoro sessions', 'focus', 'pomodoro_sessions', 50, 'waves', 120, 60),
  def('focus-25', 'Pomodoro Pro', 'Finish 60 pomodoro sessions', 'focus', 'pomodoro_sessions', 60, 'clock', 140, 70),
  def('focus-35', 'Tunnel Vision', 'Finish 80 pomodoro sessions', 'focus', 'pomodoro_sessions', 80, 'eye', 170, 85),
  def('focus-50', 'Flow State', 'Finish 125 pomodoro sessions', 'focus', 'pomodoro_sessions', 125, 'waves', 200, 100),
  def('focus-75', 'Monk Mode', 'Finish 200 pomodoro sessions', 'focus', 'pomodoro_sessions', 200, 'mountain', 275, 130),
  def('focus-100', 'Zen Master', 'Finish 250 pomodoro sessions', 'focus', 'pomodoro_sessions', 250, 'lotus', 350, 175),
  def('focus-150', 'Stillness', 'Finish 375 pomodoro sessions', 'focus', 'pomodoro_sessions', 375, 'lotus', 425, 210),
  def('focus-200', 'Time Lord', 'Finish 500 pomodoro sessions', 'focus', 'pomodoro_sessions', 500, 'watch', 500, 250),
  def('focus-365', 'Year of Focus', 'Finish 750 pomodoro sessions', 'focus', 'pomodoro_sessions', 750, 'calendar', 750, 375),

  // ── Consistency: streaks ────────────────────────────────────
  def('streak-2', 'Two-Day Spark', 'Maintain a 3-day streak', 'consistency', 'streak_days', 3, 'spark', 20, 10),
  def('streak-3', 'Threepeat', 'Maintain a 5-day streak', 'consistency', 'streak_days', 5, 'repeat', 35, 15),
  def('streak-4', 'Four Strong', 'Maintain a 7-day streak', 'consistency', 'streak_days', 7, 'flame', 45, 20),
  def('streak-5', 'Five Alive', 'Maintain a 10-day streak', 'consistency', 'streak_days', 10, 'heart', 60, 25),
  def('streak-7', 'Week Warrior', 'Maintain a 14-day streak', 'consistency', 'streak_days', 14, 'flame', 100, 50),
  def('streak-10', 'Tenacious', 'Maintain a 21-day streak', 'consistency', 'streak_days', 21, 'zap', 125, 60),
  def('streak-14', 'Fortnight', 'Maintain a 30-day streak', 'consistency', 'streak_days', 30, 'calendar-days', 150, 75),
  def('streak-21', 'Habit Formed', 'Maintain a 45-day streak', 'consistency', 'streak_days', 45, 'link', 200, 90),
  def('streak-30', 'Monthly Master', 'Maintain a 60-day streak', 'consistency', 'streak_days', 60, 'calendar', 250, 100),
  def('streak-45', 'Steady Flame', 'Maintain a 90-day streak', 'consistency', 'streak_days', 90, 'candle', 325, 140),
  def('streak-60', 'Two-Month Titan', 'Maintain a 120-day streak', 'consistency', 'streak_days', 120, 'shield', 400, 175),
  def('streak-75', 'Iron Habit', 'Maintain a 150-day streak', 'consistency', 'streak_days', 150, 'dumbbell', 475, 210),
  def('streak-90', 'Quarter Commitment', 'Maintain a 180-day streak', 'consistency', 'streak_days', 180, 'anchor', 550, 250),
  def('streak-100', 'Century Streak', 'Maintain a 200-day streak', 'consistency', 'streak_days', 200, 'infinity', 700, 350),
  def('streak-150', 'Half-Year Force', 'Maintain a 300-day streak', 'consistency', 'streak_days', 300, 'orbit', 850, 425),
  def('streak-200', 'Unbroken', 'Maintain a 365-day streak', 'consistency', 'streak_days', 365, 'shield-check', 1000, 500),
  def('streak-365', 'Year of Fire', 'Maintain a 730-day streak', 'consistency', 'streak_days', 730, 'sun', 1500, 750),

  // ── Consistency: perfect days ───────────────────────────────
  def('perfect-day', 'Perfect Day', 'Hit 100% daily completion on any day', 'consistency', 'perfect_days', 1, 'check-circle', 75, 30),
  def('perfect-2', 'Back-to-Back', 'Hit 100% on 3 days', 'consistency', 'perfect_days', 3, 'repeat', 85, 35),
  def('perfect-3', 'Triple Threat', 'Hit 100% on 5 days', 'consistency', 'perfect_days', 5, 'circle-dot', 100, 40),
  def('perfect-5', 'High Five', 'Hit 100% on 10 days', 'consistency', 'perfect_days', 10, 'star', 140, 55),
  def('perfect-week', 'Flawless Week', 'Hit 100% on 14 days', 'consistency', 'perfect_days', 14, 'star', 200, 75),
  def('perfect-10', 'Perfect Ten', 'Hit 100% on 21 days', 'consistency', 'perfect_days', 21, 'stars', 230, 90),
  def('perfect-14', 'Two Weeks Clean', 'Hit 100% on 30 days', 'consistency', 'perfect_days', 30, 'stars', 275, 110),
  def('perfect-21', 'Triple Clean', 'Hit 100% on 45 days', 'consistency', 'perfect_days', 45, 'badge', 325, 140),
  def('perfect-30', 'Perfect Month', 'Hit 100% on 60 days', 'consistency', 'perfect_days', 60, 'sun', 400, 175),
  def('perfect-50', 'Golden Standard', 'Hit 100% on 100 days', 'consistency', 'perfect_days', 100, 'gem-day', 550, 250),
  def('perfect-75', 'Near Flawless', 'Hit 100% on 150 days', 'consistency', 'perfect_days', 150, 'medal-gold', 650, 300),
  def('perfect-100', 'Perfectionist', 'Hit 100% on 200 days', 'consistency', 'perfect_days', 200, 'diamond', 800, 400),
  def('perfect-200', 'Immaculate', 'Hit 100% on 365 days', 'consistency', 'perfect_days', 365, 'crown', 1200, 600),

  // ── Milestones: levels (unchanged — XP curve makes levels harder) ──
  def('level-2', 'Level Up', 'Reach level 2', 'milestones', 'level_reached', 2, 'chevron-up', 25, 10),
  def('level-3', 'Climbing', 'Reach level 3', 'milestones', 'level_reached', 3, 'trending-up', 40, 15),
  def('level-4', 'Ascending', 'Reach level 4', 'milestones', 'level_reached', 4, 'trending-up', 60, 25),
  def('level-5', 'Rising Star', 'Reach level 5', 'milestones', 'level_reached', 5, 'award', 100, 50),
  def('level-7', 'Prodigy', 'Reach level 7', 'milestones', 'level_reached', 7, 'badge', 140, 65),
  def('level-8', 'Adept', 'Reach level 8', 'milestones', 'level_reached', 8, 'award', 160, 75),
  def('level-10', 'Double Digits', 'Reach level 10', 'milestones', 'level_reached', 10, 'hash', 200, 100),
  def('level-12', 'Seasoned', 'Reach level 12', 'milestones', 'level_reached', 12, 'medal', 240, 120),
  def('level-15', 'Veteran', 'Reach level 15', 'milestones', 'level_reached', 15, 'swords', 275, 130),
  def('level-20', 'Elite', 'Reach level 20', 'milestones', 'level_reached', 20, 'shield-check', 350, 175),
  def('level-25', 'Champion', 'Reach level 25', 'milestones', 'level_reached', 25, 'medal-gold', 450, 225),
  def('level-30', 'Grandmaster', 'Reach level 30', 'milestones', 'level_reached', 30, 'crown-level', 600, 300),
  def('level-40', 'Ascendant', 'Reach level 40', 'milestones', 'level_reached', 40, 'orbit', 800, 400),
  def('level-50', 'Mythic', 'Reach level 50', 'milestones', 'level_reached', 50, 'orbit', 1000, 500),
  def('level-75', 'Transcendent', 'Reach level 75', 'milestones', 'level_reached', 75, 'infinity', 1500, 750),
  def('level-100', 'Centurion', 'Reach level 100', 'milestones', 'level_reached', 100, 'crown', 2500, 1250),

  // ── Milestones: goals ───────────────────────────────────────
  def('goal-getter', 'Goal Getter', 'Complete your first goal', 'milestones', 'goals_completed', 1, 'target', 50, 25),
  def('goals-2', 'Aim Twice', 'Complete 3 goals', 'milestones', 'goals_completed', 3, 'target', 70, 30),
  def('goals-3', 'Aim True', 'Complete 5 goals', 'milestones', 'goals_completed', 5, 'crosshair', 90, 40),
  def('goals-5', 'Strategist', 'Complete 10 goals', 'milestones', 'goals_completed', 10, 'map', 140, 65),
  def('goals-7', 'Campaigner', 'Complete 15 goals', 'milestones', 'goals_completed', 15, 'flag', 175, 80),
  def('goals-10', 'Vision Realized', 'Complete 25 goals', 'milestones', 'goals_completed', 25, 'compass', 225, 100),
  def('goals-15', 'Mission Control', 'Complete 40 goals', 'milestones', 'goals_completed', 40, 'rocket', 300, 140),
  def('goals-25', 'Architect', 'Complete 75 goals', 'milestones', 'goals_completed', 75, 'building', 400, 200),
  def('goals-50', 'Empire Builder', 'Complete 100 goals', 'milestones', 'goals_completed', 100, 'crown', 700, 350),
]
