import {
  Anchor,
  Award,
  BadgeCheck,
  Brain,
  Building2,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronUp,
  CircleDot,
  ClipboardList,
  Clock,
  Coffee,
  Compass,
  Crosshair,
  Crown,
  Diamond,
  Dumbbell,
  Eye,
  Flag,
  Flame,
  Flower2,
  Gem,
  Hammer,
  Hash,
  Heart,
  Hourglass,
  Inbox,
  Infinity as InfinityIcon,
  Layers,
  Lightbulb,
  Link2,
  ListTodo,
  Map,
  Medal,
  Mountain,
  Orbit,
  Repeat,
  Rocket,
  Shield,
  ShieldCheck,
  Sparkle,
  Sparkles,
  Star,
  Stars,
  Sun,
  Swords,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Watch,
  Waves,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const REWARD_ICON_MAP: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  list: ListTodo,
  clipboard: ClipboardList,
  layers: Layers,
  lightbulb: Lightbulb,
  inbox: Inbox,
  eye: Eye,
  check: Check,
  'thumbs-up': BadgeCheck,
  zap: Zap,
  flag: Flag,
  medal: Medal,
  rocket: Rocket,
  bolt: Zap,
  trophy: Trophy,
  hammer: Hammer,
  dumbbell: Dumbbell,
  crown: Crown,
  gem: Gem,
  timer: Timer,
  coffee: Coffee,
  hourglass: Hourglass,
  brain: Brain,
  focus: Target,
  clock: Clock,
  waves: Waves,
  mountain: Mountain,
  lotus: Flower2,
  watch: Watch,
  spark: Sparkle,
  repeat: Repeat,
  heart: Heart,
  flame: Flame,
  'calendar-days': CalendarDays,
  link: Link2,
  calendar: Calendar,
  candle: Flame,
  shield: Shield,
  anchor: Anchor,
  infinity: InfinityIcon,
  'check-circle': CheckCircle2,
  'circle-dot': CircleDot,
  star: Star,
  stars: Stars,
  sun: Sun,
  'gem-day': Gem,
  diamond: Diamond,
  'chevron-up': ChevronUp,
  'trending-up': TrendingUp,
  award: Award,
  badge: BadgeCheck,
  hash: Hash,
  swords: Swords,
  'shield-check': ShieldCheck,
  'medal-gold': Medal,
  'crown-level': Crown,
  orbit: Orbit,
  target: Target,
  crosshair: Crosshair,
  map: Map,
  compass: Compass,
  building: Building2,
}

export function getRewardIcon(key: string): LucideIcon {
  return REWARD_ICON_MAP[key] ?? Trophy
}
